site_name: RCC User Guide
repo_url: https://rcc.uchicago.edu/
repo_name: Main RCC website
docs_dir: docs
theme:
  name: 'material'
  # name: 'readthedocs'
  features:
    - content.code.copy
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
  
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css


nav:
  - Home: 'index.md' 
  - Ecosystems: ecosystems.md 
  - Accounts: accounts.md 
  - Allocations: allocations.md 

  - Connection: 
    - Overview: connection/main.md
    - 'SSH': connection/ssh/main.md 
    - 'Open OnDemand': connection/open_ondemand/open_ondemand.md
    - 'ThinLinc': 
      - Basics: connection/thinlinc/main.md
      - Troubleshooting: connection/thinlinc/troubleshooting.md
    - Globus: connection/globus/access-files.md
  
  - 'Data Transfer':
    # #TODO- SFTP Clients: data_transfer/sftp/clients.md
    - Globus: data_transfer/globus/transfer-files.md
    - SAMBA: data_transfer/persistent_mapping/samba.md
    - CLI: data_transfer/cli/cli.md
    # - Cloud:
      # - Globus: data_transfer/cloud/cloud-sync.md
      # - RClone: data_transfer/cloud/rclone.md

  - Data Sharing: 
    - Filesystems: data_sharing/access_control.md
    - Globus: data_sharing/globus_sharing.md
    - Web Hosting: data_sharing/http_sharing.md
    - Datasets: 
      - AlphaFold: data_sharing/databases/alphafold.md
      - BFI: data_sharing/databases/bfi.md
      - Booth: data_sharing/databases/booth.md

  - 'Storage': 
    - Basics: storage/main.md
    - FAQ: storage/faq.md

  - 'Computing': 
    - Scheduler: slurm/main.md
    - Partitions: slurm/partitions.md
    - Interactive Jobs: slurm/sinteractive.md
    - Batch Jobs: slurm/sbatch.md 
    - FAQ: slurm/faq.md

  - 'Software':
    - Overview: software/index.md
    - Compilers: software/compilers.md
    - Libraries: software/libraries.md
    - Developer Tools: software/dev-tools.md
    - Commonly Used:
      - Alphafold: software/apps-and-envs/alphafold.md
      - Apptainer & Singularity : software/apps-and-envs/singularity.md
      - BinSanity: software/apps-and-envs/binsanity.md
      - CESM: software/apps-and-envs/cesm.md
      - CryoSPARC: software/apps-and-envs/cryosparc.md
      - CUDA-Q: software/apps-and-envs/cudaq.md
      - Gaussian: software/apps-and-envs/gaussian.md
      - GROMACS: software/apps-and-envs/gromacs.md
      - LAMMPS: software/apps-and-envs/lammps.md
      - MeshLab: software/apps-and-envs/meshlab.md
      - MATLAB: software/apps-and-envs/matlab.md
      - Mathematica: software/apps-and-envs/mathematica.md
      - NAMD: software/apps-and-envs/namd.md
      - NWChem: software/apps-and-envs/nwchem.md
      - OpenMM: software/apps-and-envs/openmm.md
      - OpenPose: software/apps-and-envs/openpose.md
      - ORCA: software/apps-and-envs/orca.md
      - Perl: software/apps-and-envs/perl.md
      - Python & Notebooks: software/apps-and-envs/python.md
      - R and RStudio: software/apps-and-envs/r.md
      - Charliecloud: software/apps-and-envs/charliecloud.md
      - Space Ranger: software/apps-and-envs/spaceranger.md
      - Spark: software/apps-and-envs/spark.md
      - Stata: software/apps-and-envs/stata.md
      - Tensorflow and PyTorch: software/apps-and-envs/tf-and-torch.md
      - WRF: software/apps-and-envs/wrf.md
      - "VS Code (SCode)":
        - Basics: software/apps-and-envs/scode/main.md
        - Extensions: software/apps-and-envs/scode/extensions.md
        - SCode Environments: software/apps-and-envs/scode/environments.md
        - Python & Jupyter Notebook: software/apps-and-envs/scode/python.md
        - API: software/apps-and-envs/scode/api.md
    - FAQ: software/faq.md

  - "Tutorials":
    - KICP: tutorials/kicp.md
    - MSCA: tutorials/msca.md
    - GIS:
      - Basics: tutorials/gis/index.md
      - Geocoding: tutorials/gis/geocoding.md
      - Geospatial: tutorials/gis/MidwayGeoSpatial.md
    - SDE3:
      - Overview: tutorials/sde3/overview.md
      - Connection: tutorials/sde3/connection.md
      - Data Transfer: tutorials/sde3/data-transfer.md
      - Computing: tutorials/sde3/compute.md
      - Software: tutorials/sde3/software.md
    - SDE2:
      - Overview: tutorials/sde2/overview.md
      - Connection: tutorials/sde2/connection.md
      - Data Transfer: tutorials/sde2/data-transfer.md
      - Computing: tutorials/sde2/compute.md
      - Software: tutorials/sde2/software.md
  
  - Glossary: glossary.md 
  - Best Practices: mistakes.md
  
extra:
  analytics:
    provider: google
    property: G-BE96ZBJB57

# extra:
#  consent:
#    title: Cookie consent
#    description: > # (1)
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better. 

extra_javascript:
  - stylesheets/gtag.js

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - wikilinks
  - tables
  - attr_list
  - md_in_html
  - pymdownx.magiclink
  - pymdownx.critic

plugins:
  - monorepo
  - search:
      separator: '[\s\.]+'
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      # Requires: pip install mkdocs-git-revision-date-localized-plugin
